### ISSUE TITLE
Feedback from 2022-01-20

### ISSUE THREAD

**Issue by annakrystalli** [RSE-Sheffield/git-github-zero-to-hero#10]
## Instructor:

- Issue with accepting (finding) GitHub invitations: https://github.community/t/where-do-i-see-all-incoming-invitations-collaborator/661/4. 
  **Solution**: You can also see the invite if you know which repo you were invited to:
   https://github.com/username/reponame/invitations <- NEEDS TESTING
-  Issues with GitKraken on UBUNTU:
    -  installation issue: **Solution** add note to setup instructions about testing UBUNTU especially and getting in touch if they have issues before course.
    - Appearance issue
- Expand by half hr to give more breathing space to afternoon.
- When demoing executing instructions in issue, make single commit to also demonstrate committing changes to multiple files

**Comment by bobturneruk** [comment]
![InkedScreenshot from 2022-01-20 14-57-15_LI](https://user-images.githubusercontent.com/34244196/150498851-6d87984c-1898-4343-84df-4878ff5c915b.jpg)

Ubuntu linux screen capture.
