### ISSUE TITLE
Feedback from 2022-02-01

### ISSUE THREAD

**Issue by davidwilby** [RSE-Sheffield/git-github-zero-to-hero#14]
1. Gitkraken Client has a 7-day trial period - is this waived for github pro/education users?
2. Issue with user having `Block command line pushes that expose my email` enabled - possible fix here: https://stackoverflow.com/questions/43378060/meaning-of-the-github-message-push-declined-due-to-email-privacy-restrictions - @davidwilby will investigate. (Probably unlikely to be a frequent problem, but I think it's reasonable for a user to have this option enabled on github)
3. Possibly worth making the afternoon session even longer, still ran pretty close to the time available, would have been good to have a bit longer.
4. Include in materials a clearer indication that the team owners should create all the issues at the same time and that the team members should follow along with their particular issue instructions, I got a little bit confused and forgot to make this clear, which meant that not everyone had an issue assigned to follow along with Bob's demo. This is more just to help me and my feeble brain.

**Comment by bobturneruk** [comment]
![image](https://user-images.githubusercontent.com/34244196/152337276-bf1d6d4b-5da9-4cb6-b484-1ca6e784dad7.png)
This is the offending setting.

**Comment by davidwilby** [comment]
I've added instructions to the FAQ now.
