### ISSUE TITLE
Prepare materials for session on 2022-04-12 for @bobturneruk

### ISSUE THREAD

**Issue by davidwilby** [RSE-Sheffield/git-github-zero-to-hero#23]
All instructors (lead and support) need to do some preparation (especially to repos in their own accounts) if they have created materials during a previously run course. Lead instructor has some extra prep steps.

Complete as necessary (dependant on what has been created in the past). 

**Tick off tasks as they are completed or if they are not required.**

- [ ] *optional* Delete `git-lesson` repo from instructor's GitHub account. Delete local copy if you want to use same location for demo.
- [x]  *optional* Delete `collaborative_github_exercise` fork repo **FROM INSTRUCTOR'S ACCOUNT ONLY**. Do NOT delete the RSE-Sheffield original repo.  Delete local copy (of fork!) if you want to use same location for demo. 
- [ ] @bobturneruk Delete `python-calculator` repo from instructor's account. Delete local copy if you want to use same location for demo.

Once all tasks are complete, please close issue.

**Comment by bobturneruk** [comment]
Ayup @davidwilby - I don't think I need to delete `python-calculator` from my account, as I never fork it. Just need to delete from my disk. Does this make sense?

**Comment by davidwilby** [comment]
quite right you are!
