### ISSUE TITLE
Prepare materials for session on 2021-12-09

### ISSUE THREAD

**Issue by annakrystalli** [RSE-Sheffield/git-github-zero-to-hero#3]
All instructors (lead and secondary) need to do some preparation (especially to repos in theirs accounts) if they have created materials during a previously run course. Lead instructor has some extra prep steps.

Complete as necessary (dependant in what has been created in the past). Tick off tasks as they are completed or if they are not required.

- [x] Delete `git-lesson` repo from instructor's GitHub account. Delete local copy if you want to use same location for demo.
- [x] Delete `collaborative_github_exercise` fork repo **from instructor's account**.  Delete local copy (of fork!) if you want to use same location for demo. 
- [x] [LEAD INSTRUCTOR] Clear previously submitted parameter files from `params/` folder in `RSE-Sheffield/collaborative_github_exercise` repo. DO NOT DELETE `params_tmpl.R`. Synch local and remote repos.
- [x] Delete `python-calculator` repo from instructor's account. Delete local copy if you want to use same location for demo.

**Comment by annakrystalli** [comment]
Hey @bobturneruk . I've setup some issue templates to onboard new instructors and prepare for the next session.

As a support instructor, could you go through the prep steps and see if it helps? Fell free to add suggestions here on how to improve or make a direct PR to the issue templates

**Comment by bobturneruk** [comment]
Ayup @annakrystalli - looks super helpful - I'll do this before the course.

**Comment by bobturneruk** [comment]
Gone through and deleted - I think I'd done some of it already. I'll note if I hit any speedbumps as we go through tomorrow.

**Comment by annakrystalli** [comment]
Wanna tick off the tasks as they are done? We can close the issue after.
