### ISSUE TITLE
Setup New Lead instructor Neil Shephard

### ISSUE THREAD

**Issue by ns-rse** [RSE-Sheffield/git-github-zero-to-hero#41]
Documentation for most setup instructions is available in the course material [**setup**](https://srse-git-github-zero2hero.netlify.app/setup/) chapter.

- [x] Install git
- [x] Install [R](https://www.r-project.org/) & [RStudio](https://www.rstudio.com/)
- [x] Create GitHub account
- [x] Install GitKraken
- [x] Sign-in to GitKraken with GitHub account.
- [x] Ensure SSH keypair for accessing GitHub is configured in GitKraken.
- [x] Clone [`RSE-Sheffield/collaborative_github_exercise` repo](https://github.com/RSE-Sheffield/collaborative_github_exercise). Clone it to somewhere where you won't get it mixed up with the fork you will clone during teaching.
- [x] Ensure you have admin access to `RSE-Sheffield/collaborative_github_exercise`
- [x] Open RSE-Sheffield/collaborative_github_exercise project in Rstudio
- [x] Run `renv::restore()` to install dependencies.
- [x] Test that you can knit `plot_trait_evolution.Rmd` succesfully. _If it succeeds, it's fine to revert the resulting `plot_trait_evolution.html` to it's previous state instead of committing the changes. However, make sure they are cleared in the git tab one way or the other so as not to confuse the demo._

**Comment by ns-rse** [comment]
Noting here so I can update later.

When I went to knit `plot_trait_evolution.Rmd` I was informed the following packages were required but not installed...

* `rmarkdown`
* `dplyr`
* `ggplot2`
* `plotly`
* `sessioninfo`

Need to check whether they are included in the `renv` and if not add them so they are installed and included when restoring the environment.

**Comment by ns-rse** [comment]
I'll test knitting after tomorrows course when there will be some data to include.

Currently I don't have admin access to [RSE-Sheffield/collaborative_github_exercise](https://github.com/RSE-Sheffield/collaborative_github_exercise) would you be able to grant me that please @davidwilby or @bobturneruk ?

**Comment by davidwilby** [comment]
Done.

**Comment by ns-rse** [comment]
Tested with some data now and I can knit although in addition to the above packages needing to be installed I also had to update the `markdown` package.

I've added an issue for updating the `renv` to the repository, see [#312](https://github.com/RSE-Sheffield/collaborative_github_exercise/issues/312).
