### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by ns-rse** [RSE-Sheffield/git-github-zero-to-hero#60]
Realised delivering the course this morning that the repository itself is missing a license.

We should therefore add a license to the repository, open to which license to use and input welcome.

**Comment by davidwilby** [comment]
See this closed PR on the topic: https://github.com/RSE-Sheffield/git-github-zero-to-hero/pull/6

We could still include one, but there was some discussion there.

**Comment by ns-rse** [comment]
Thanks that's quite subtle.

I don't think it would do any harm to include a `LICENSE.md` as we advocate having such a file.
