### ISSUE TITLE
Prepare materials for session on 2022-01-20 for @bobturneruk

### ISSUE THREAD

**Issue by bobturneruk** [RSE-Sheffield/git-github-zero-to-hero#7]
All instructors (lead and support) need to do some preparation (especially to repos in their own accounts) if they have created materials during a previously run course. Lead instructor has some extra prep steps.

Complete as necessary (dependant in what has been created in the past). Tick off tasks as they are completed or if they are not required.

- [x] Delete `git-lesson` repo from instructor's GitHub account. Delete local copy if you want to use same location for demo.
- [ ] Delete `collaborative_github_exercise` fork repo **FROM INSTRUCTOR'S ACCOUNT ONLY**. Do NOT delete the RSE-Sheffield original repo.  Delete local copy (of fork!) if you want to use same location for demo. 
- [ ] [LEAD INSTRUCTOR] Clear previously submitted parameter files from `params/` folder in `RSE-Sheffield/collaborative_github_exercise` repo. DO NOT DELETE `params_tmpl.R`. Synch local and remote repos.
- [x] Delete `python-calculator` repo from instructor's account. Delete local copy if you want to use same location for demo.
- [x] Clear collaborative team formation [googledoc](https://docs.google.com/document/d/1-CkHO417wtfJZ35X4q5tk_hcgP9W3mfEG5AsN2SIU1A/edit)

**Comment by bobturneruk** [comment]
@annakrystalli - support instructors only need to delete `python-calculator` from their hard disk?

**Comment by annakrystalli** [comment]
The most important is to delete from your GitHub account. You only need to delete local copy if you want to create it at the same path in the next session

**Comment by bobturneruk** [comment]
Yes - I never had it in my GitHub account (i.e. forked / templated) as I was only support.

**Comment by annakrystalli** [comment]
All good then. You could have been a lead instructor the previous time though so it's best to check every time.

**Comment by annakrystalli** [comment]
All done? Feel free to tick off tasks that  are done / not required and close issue when done :)

**Comment by bobturneruk** [comment]
Done all stuff that applies, thanks.
