### ISSUE TITLE
Open Source Basics youtube video is made private

### ISSUE THREAD

**Issue by twinkarma** [RSE-Sheffield/git-github-zero-to-hero#94]
Open Source Basics youtube video is made private (page [https://srse-git-github-zero2hero.netlify.app/00-intro-to-version-control/03-what-is-github/](https://srse-git-github-zero2hero.netlify.app/00-intro-to-version-control/03-what-is-github/)). Any alternatives or should it just be removed from the page?

**Comment by tdjames1** [comment]
I think this link works for the Open Source Basics video:
https://youtu.be/upxUAI-fAtE?feature=shared

**Comment by ns-rse** [comment]
Closed by #105
